fragment PortfolioParts on Portfolio {
  __typename
  title
  slug
  description
  date
  excerpt
  category
  tags
  year
  client
  image
  imageAlt
  link
  featured
  body
}

fragment BlogParts on Blog {
  __typename
  title
  slug
  description
  excerpt
  date
  author
  category
  tags
  image
  imageAlt
  readTime
  body
}

fragment PagesParts on Pages {
  __typename
  title
  description
  lastUpdate
  tocTitle
  selectedProjects
  hero {
    __typename
    title
    subtitle
    image
  }
  technology {
    __typename
    title
    description
  }
  offer {
    __typename
    title
    subtitle
    sectionLabel
    services {
      __typename
      title
      description
      icon
      features
      link
      buttonText
    }
  }
  brief {
    __typename
    description
    badge
    heroTitle
    heroTitleHighlight
    tabs {
      __typename
      label
      value
    }
    form {
      __typename
      progressLabel
      requiredMark
      placeholderTextarea
      placeholderText
      placeholderTechnology
      placeholderIntegrations
      buttonPrev
      buttonNext
      buttonSubmit
      buttonSubmitting
      successTitle
      successMessage
    }
    contactForm {
      __typename
      title
      placeholderName
      placeholderEmail
      placeholderMessage
      buttonSend
      buttonSending
      successTitle
      successMessage
    }
    contactInfo {
      __typename
      title
      emailLabel
      phoneLabel
      addressLabel
      quickResponseLabel
      quickResponseText
    }
    contact {
      __typename
      email
      phone
      address
      addressLine2
      city
    }
  }
  portfolioHighlights {
    __typename
    title
    description
  }
  howWeWork {
    __typename
    title
    description
    steps {
      __typename
      title
      description
      icon
      duration
    }
  }
  faq {
    __typename
    title
    description
    items {
      __typename
      question
      answer
    }
  }
  contact {
    __typename
    title
    description
    email
    phone
    address
    addressLine2
    city
    successTitle
    successMessage
    nameLabel
    emailLabel
    messageLabel
    buttonText
    contactDataTitle
    quickResponseLabel
    quickResponseText
  }
  portfolio {
    __typename
    title
    description
    sectionLabel
  }
  blog {
    __typename
    title
    description
    sectionLabel
    shareTitle
    shareButtons {
      __typename
      twitter
      linkedin
      facebook
      copyLink
    }
    tableOfContentsTitle
    authorBox {
      __typename
      title
      bio
      contact
    }
    relatedArticlesTitle
    otherProjectsTitle
  }
  searchBar {
    __typename
    blog {
      __typename
      searchPlaceholder
      clearSearch
      filterByTech
      clearFilters
      showLess
      showMore
      activeFilters
      removeFilter
    }
    portfolio {
      __typename
      searchPlaceholder
      clearSearch
      filterByTech
      clearFilters
      showLess
      showMore
      activeFilters
      removeFilter
    }
  }
  body
}
