import type { Metadata } from "next";
import "./globals.css";
import { Header } from "@/components/header";
import { Footer } from "@/components/footer";
import { CursorLightProvider } from "@/hooks/cursor-light";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pl">
      <body className="antialiased">
        <CursorLightProvider>
          <Header />
          {children}
          <Footer />
        </CursorLightProvider>
      </body>
    </html>
  );
}
